---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - main.yaml

namespace: kube-system

commonLabels:
    app.kubernetes.io/name: eventrouter
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/component: exporter
    app.kubernetes.io/part-of: monitoring
